networks:
  dev_network:

services:

  postgre:
    image: postgres:14.3-alpine3.16
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: users_api_db_main
    networks:
      dev_network:
        aliases:
          - db-postgre

  redis:
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
    depends_on:
      - postgre
    networks:
      dev_network:
        aliases:
          - db-redis

  mongo:
    image: mongo:4.4.14
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    depends_on:
      - redis
    networks:
      dev_network:
        aliases:
          - db-mongo
